### ISSUE TITLE
没有途径直接下载 flac 格式，是必须要用会员才行吗？

### ISSUE THREAD

**Issue by little-buddy** [XiaoMengXinX/Music163bot-Go#12]
<img width="627" alt="image" src="https://github.com/XiaoMengXinX/Music163bot-Go/assets/30054881/80546e62-e02e-489c-ac13-21c8a0a48097">

**Comment by iamPorter** [comment]
按照先前[NeteaseCloudMusicAPI](https://github.com/Binaryify/NeteaseCloudMusicApi)（现在代码仓库已经销毁）的运行效果来看，网易云后台可能会识别用户的登录状态而分别分发不同的音乐，例如说未登录的游客只能下载320k的MP3（这应该已经属于破格了），登录的非VIP可以请求SQ和Hi-Res以及试听片段，VIP最高请求高清臻音，SVIP可以任意请求音质。如果这个机器人工作原理也是在通过某种客户端请求或者是官方的某些接口工作的话，你不登录应该是不能直接请求FLAC的。
