### ISSUE TITLE
How to get more song informations (Tags)?

### ISSUE THREAD

**Issue by PSVLTT** [XiaoMengXinX/Music163bot-Go#17]
Hello,
The first, I want to thank you to creat this cool bot.
My question is: How to get more song information (Tags) like : date release, album artists, track, total tracks... etc
The song's tags is not fully like normal.
Did I miss something?

Thank you very much!

![image](https://github.com/XiaoMengXinX/Music163bot-Go/assets/142076226/871e4e27-91b3-4d55-bfab-b01a93f4758b)

**Comment by XiaoMengXinX** [comment]
Sorry, but the behavior of the metadata encoding is as the same as the Netease Music app, if you need related functions, please use other projects.

**Comment by PSVLTT** [comment]
> Sorry, but the behavior of the metadata encoding is as the same as the Netease Music app, if you need related functions, please use other projects.

Thank you for reply, I have understood.

**Comment by XiaoMengXinX** [comment]
> > Sorry, but the behavior of the metadata encoding is as the same as the Netease Music app, if you need related functions, please use other projects.
> 
> Thank you for reply, I have understood.

By the way, you can use my new tool to download from Spotify, which include the metadata you need. 

https://github.com/XiaoMengXinX/spotdl

**Comment by PSVLTT** [comment]
> > > Sorry, but the behavior of the metadata encoding is as the same as the Netease Music app, if you need related functions, please use other projects.
> > 
> > 
> > Thank you for reply, I have understood.
> 
> By the way, you can use my new tool to download from Spotify, which include the metadata you need.
> 
> https://github.com/XiaoMengXinX/spotdl

Thank you! I will try it.
