### ISSUE TITLE
[Feature request] 建议增加直接获取歌词文本功能

### ISSUE THREAD

**Issue by CombineBasla** [XiaoMengXinX/Music163bot-Go#18]
建议给 bot 添加或替换命令，让bot 能直接发送的歌词文本而不是歌词文本文件，例如：

![IMG_20240707_204041](https://github.com/XiaoMengXinX/Music163bot-Go/assets/140225819/b86d8de4-3f06-4a2e-96a2-5779cab7b08b)

### 方案 1

将当前 `/lyric` 命令与其实现迁移至 `/lyricfile`，实现新的 `/lyric` 命令以直接获取文本

### 方案 2

保留当前 `/lyric` 命令实现，添加 `/lyrictext` 实现以直接获取文本

### 方案 3

直接重新实现 `/lyric` 命令

**Comment by XiaoMengXinX** [comment]
考虑到有些歌曲的歌词较长，以及 `/lyric` 命令本身使用率不高，遂采取了当前行为。方案 1、2 是很好的解决方式，但本 bot 目前代码我已不再打算维护，您可以自行 fork 并进行修改。
