### ISSUE TITLE
cannot load github.com/traefik/yaegi/stdlib/syscall: no Go source files

### ISSUE THREAD

**Issue by Allroha** [XiaoMengXinX/Music163bot-Go#3]
🥺

**Comment by XiaoMengXinX** [comment]
Is there a more detailed log?

**Comment by Allroha** [comment]
> Is there a more detailed log?

Doesn't it seem? But it doesn't matter. I don't care anymore

**Comment by XiaoMengXinX** [comment]
> Doesn't it seem? But it doesn't matter. I don't care anymore

Sorry, but this error should not appear unless you did something weird :(
And I'm actually not sure what will cause this.
