### ISSUE TITLE
[BUG] 当bot不在群内时内联搜索不可用

### ISSUE THREAD

**Issue by Howard20181** [XiaoMengXinX/Music163bot-Go#4]
当bot不在群里时用内联模式搜索时，点击搜索结果会以向群中发送指令+歌曲id的形式获取歌曲，而不是与内联模式下输入歌曲id时直接发送歌曲一样。

PS. 反馈群的认证机器人坏了，进不了

**Comment by Howard20181** [comment]
如果要做到搜索时每条结果都可以在内联模式下直接发送歌曲需要缓存一堆歌曲，资源占用太大
如果该行为是by design的话可以close了

**Comment by XiaoMengXinX** [comment]
确实是 by design（
主要是tg没法通过url获取超过10M的文件，再加上bot也会对音频文件本身进行很多处理（id3v2之类），而下载歌曲再上传不太现实（
