### ISSUE TITLE
歌曲大小到达50MB左右会下载失败

### ISSUE THREAD

**Issue by jisa8438** [XiaoMengXinX/Music163bot-Go#9]
![image](https://github.com/XiaoMengXinX/Music163bot-Go/assets/39065858/85fb724c-1814-4293-9903-7e6410c313e8)

**Comment by eternal12345** [comment]
![image](https://github.com/XiaoMengXinX/Music163bot-Go/assets/34204787/171d2ac0-8a59-4276-abed-c20d109c0d8e)

**Comment by nickadamscode** [comment]
![image](https://github.com/XiaoMengXinX/Music163bot-Go/assets/136897093/ed05b41c-1c5a-48f8-b963-160b9909b669)

**Comment by nickadamscode** [comment]
![image](https://github.com/XiaoMengXinX/Music163bot-Go/assets/136897093/baf4791c-e41f-44e9-a950-42cf973ee722)
telegram bot的限制，只能发送小于50MB的文件

**Comment by jisa8438** [comment]
> ![image](https://user-images.githubusercontent.com/136897093/258309608-baf4791c-e41f-44e9-a950-42cf973ee722.png) telegram bot的限制，只能发送小于50MB的文件

已经自建API解决了

**Comment by leifeng-N** [comment]
> > ![图像](https://user-images.githubusercontent.com/136897093/258309608-baf4791c-e41f-44e9-a950-42cf973ee722.png)telegram bot的限制，只能发送小于50MB的文件
> 
> 已经自建API解决了

搜的歌曲咋只有一页，而且很多歌都是错的

**Comment by XiaoMengXinX** [comment]
> > > ![图像](https://user-images.githubusercontent.com/136897093/258309608-baf4791c-e41f-44e9-a950-42cf973ee722.png)telegram bot的限制，只能发送小于50MB的文件
> > 
> > 
> > 已经自建API解决了
> 
> 搜的歌曲咋只有一页，而且很多歌都是错的

你的服务器ip问题
